MONGODB_HOST: mongodb-{{ env }}.cloudquestdev.com
REDIS_HOST: redis-{{ env }}.cloudquestdev.com
CATALOGUE_HOST: catalogue-{{ env }}.cloudquestdev.com
CART_HOST: cart-{{ env }}.cloudquestdev.com
MYSQL_HOST: mysql-{{ env }}.cloudquestdev.com
USER_HOST: user-{{ env }}.cloudquestdev.com
RABBITMQ_HOST: rabbitmq-{{ env }}.cloudquestdev.com
SHIPPING_HOST: shipping-{{ env }}.cloudquestdev.com
PAYMENT_HOST: payment-{{ env }}.cloudquestdev.com