MONGODB_HOST: mongodb-{{ env }}.cloudquestdev.com
REDIS_HOST: redis-{{ env }}.cloudquestdev.com
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.cloudquestdev.com
CART_HOST: cart.backend-alb-{{ env }}.cloudquestdev.com
MYSQL_HOST: mysql-{{ env }}.cloudquestdev.com
USER_HOST: user.backend-alb-{{ env }}.cloudquestdev.com
RABBITMQ_HOST: rabbitmq-{{ env }}.cloudquestdev.com
SHIPPING_HOST: shipping.backend-alb-{{ env }}.cloudquestdev.com
PAYMENT_HOST: payment.backend-alb-{{ env }}.cloudquestdev.com